# Generated by Django 5.0.3 on 2024-03-09 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='タイトル')),
                ('catch_copy', models.CharField(verbose_name='キャッチコピー')),
                ('concept', models.CharField(verbose_name='コンセプト')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prototype',
            },
        ),
    ]
